/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PART_C_H_RPCGEN
#define _PART_C_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *Path;

struct parameters {
	int number1;
	int number2;
	Path path;
};
typedef struct parameters parameters;

#define PART_C_PROG 0x12345678
#define PART_C_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define part_c 1
extern  char ** part_c_1(parameters *, CLIENT *);
extern  char ** part_c_1_svc(parameters *, struct svc_req *);
extern int part_c_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define part_c 1
extern  char ** part_c_1();
extern  char ** part_c_1_svc();
extern int part_c_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Path (XDR *, Path*);
extern  bool_t xdr_parameters (XDR *, parameters*);

#else /* K&R C */
extern bool_t xdr_Path ();
extern bool_t xdr_parameters ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PART_C_H_RPCGEN */
